[package]
name = "boids"
version = "0.1.0"
authors = ["tiredsounds"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
nalgebra-glm = "*"
proptest = "*"
assert_approx_eq = "*"